print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? $"))
percent_tip= int(input("What percentage tip would you like to give? 10, 12, or 15? "))
num_people = int(input("How many people to split the bill? "))
split_amount = (total_bill/num_people)*(1+percent_tip/100)
round_split = "{:.2f}".format(split_amount)
print(f"Each person should pay: ${round_split}")